<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6939190d-601d-455b-b3a3-a13ddb20f10b</UserSecretsId>
	  <GenerateRuntimeConfigDevFile>true</GenerateRuntimeConfigDevFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\**" />
    <Content Remove="Migrations\**" />
    <EmbeddedResource Remove="Migrations\**" />
    <None Remove="Migrations\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\CategoriesController.cs" />
    <Compile Remove="Data\StorageContext.cs" />
    <Compile Remove="Models\DbInitializer.cs" />
    <Compile Remove="Models\MockCategoryRepository.cs" />
    <Compile Remove="Models\MockDb.cs" />
    <Compile Remove="Models\MockProductRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.Build" Version="18.0.2" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="18.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="wwwroot/public/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Storage.Persistence\Storage.Persistence.csproj" />
  </ItemGroup>

</Project>
