# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy ASP.Net Core app to Azure Web App - coffee-party

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: windows-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up .NET Core
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: '10.0.x'

#       - name: Build with dotnet
#         run: dotnet build --configuration Release

#       - name: dotnet publish
#         run: dotnet publish -c Release --property:PublishDir="${{env.DOTNET_ROOT}}\Storage"

#       # Source - https://stackoverflow.com/a/60913464
#         # Posted by Mahi, modified by community. See post 'Timeline' for change history
#         # Retrieved 2025-12-30, License - CC BY-SA 4.0

#         #substitute production appsettings entries to appsettings json file
#       - name: App Settings Variable Substitution
#         uses: microsoft/variable-substitution@v1
#         with:
#           files: '${{env.DOTNET_ROOT}}\Storage\appsettings.json'
#         env:
#           ConnectionStrings.StorageContext: ${{ secrets.STORAGECONTEXT }}
#           App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: .net-app
#           path: ${{env.DOTNET_ROOT}}\Storage

#   deploy:
#     runs-on: windows-latest
#     needs: build
#     permissions:
#       id-token: write #This is required for requesting the JWT
#       contents: read #This is required for actions/checkout

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: .net-app
      
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A108B3FD3DD043F285C23527C1CBE210 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D320110445FD4D44BDB4B5E6726B55F8 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3D5F102B79BE427B88B6C61B2CAAC5F0 }}

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'coffee-party'
#           slot-name: 'Production'
#           package: .
          

name: Deploy ASP.NET MVC App deploy to Azure Web App

on: [push]

env:
  AZURE_WEBAPP_NAME: coffee-party    # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Set this to the path to your web app project, defaults to the repository root
  NUGET_VERSION: '7.0.x'           # Set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # Check out the repo
    - uses: actions/checkout@main
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run MSBuild
      run: msbuild .\Storage.sln
       
    - name: 'Run Azure webapp deploy action using Azure Credentials'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Storage/'
  
    # Azure logout 
    - name: logout
      run: |
        az logout