# From: How To Deploy Your .NET Application To Azure Using GitHub Actions (2025)
# https://www.youtube.com/watch?v=6qPzeB0dN9o
name: Build and Deploy ASP.NET MVC App to Azure Web App

on: 
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: coffee-party-app
  AZURE_WEBAPP_PACKAGE_PATH: './Storage.Mvc/publish' 
  DOTNET_VERSION: '10.0.X'
  SOLUTION_PATH: 'Storage.slnx'
  MVC_PROJECT_PATH: 'Storage.Mvc/Storage.Mvc.csproj'
  PUBLISH_DIR: './publish'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      # ToDo: run tests
      # - name: Test
      #   run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ env.MVC_PROJECT_PATH}} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # ToDo: apply migrations here?

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env. AZURE_WEBAPP_PACKAGE_PATH}}
